### ISSUE TITLE
box example doesn't work in IE 11

### ISSUE THREAD

**Issue by mejobloggs** [a-jie/Agile#5]
Hi, really nice work on Agile, I like it.

I'm particularly interested in your box example, however it doesn't seem to work on IE 11?

http://a-jie.github.io/Agile/examples/3d/box.html

When viewed in IE 11 it ony shows 2d. It's just a flat square, not a cube

I'm hoping I can use your Agile cube on IE 11 (10 would be nice, but 11 is most important)

**Comment by a-jie** [comment]
I'm sorry, because I have been using the MacBook, I stay away from windows for a long time. The problem you say I will be the first time to repair.
