### ISSUE TITLE
isometric map

### ISSUE THREAD

**Issue by AhmetOZALP** [a-jie/Agile#7]
hello Is there movement in the example I want to make 3d map?

**Comment by rafaelcastrocouto** [comment]
guess you are looking for this...
https://github.com/a-jie/Agile/blob/master/examples/box2d/box2d.html
preview:
http://htmlpreview.github.io/?https://github.com/a-jie/Agile/blob/master/examples/box2d/box2d.html

**Comment by a-jie** [comment]
3D map? Sorry, I don't know what you need.

**Comment by AhmetOZALP** [comment]
Example isometric 2d game http://s1.dmcdn.net/ini5/1280x720-2gn.jpg


like this

**Comment by rafaelcastrocouto** [comment]
you can use http://eureca.io/ and  http://ezgui.ezelia.com/
like they do!

**Comment by AhmetOZALP** [comment]
thank you.
